'use client'
import {useEffect,useMemo,useState} from 'react'

type Row=Record<string,string>; const prices=[1.79,2.19,2.59]; const channels=['DTC Online','Retail/Grocery','Gym & Office'];
const money=(n:number)=>`€${n.toFixed(2)}`; const pct=(n:number)=>`${n.toFixed(1)}%`;
function parse(s:string){const lines=s.trim().split(/\r?\n/); const h=lines[0].split(','); return lines.slice(1).map(l=>{let a=l.match(/(".*?"|[^",]+)(?=,|$)/g)?.map(x=>x.replace(/^"|"$/g,''))||[];return Object.fromEntries(h.map((k,i)=>[k,a[i]||'']))})}
function Bar({value,max=100,color='#e96f3c'}:{value:number,max?:number,color?:string}){return <div className="bar"><i style={{width:`${Math.min(100,value/max*100)}%`,background:color}}/></div>}
export default function Home(){
 const [d,setD]=useState<Record<string,Row[]>>({}); const [price,setPrice]=useState(2.19); const [mix,setMix]=useState([35,35,30]); const [tab,setTab]=useState('Overview');
 useEffect(()=>{Promise.all(['price_test_results','channel_economics','competitor_prices_by_channel','marketing_funnel_monthly','market_context','seasonality_and_weather','customer_quotes'].map(x=>fetch('/data/'+x+'.csv').then(r=>r.text()).then(parse))).then(v=>setD(Object.fromEntries(['tests','econ','competitors','funnel','market','season','quotes'].map((k,i)=>[k,v[i]]))))},[])
 const test=d.tests||[], econ=d.econ||[], comp=d.competitors||[], funnel=d.funnel||[], market=d.market||[], season=d.season||[], survey=[{preferred_channel:'Retail/Grocery',count:'195'},{preferred_channel:'DTC Online',count:'119'},{preferred_channel:'Gym & Office',count:'106'}], quotes=d.quotes||[];
 const selected=test.filter(r=>+r.price_eur===price); const blended=selected.reduce((s,r,i)=>s+(+r.unit_contribution_eur||0)*mix[i]/100,0); const acc=selected[0]?+selected[0].estimated_acceptance_pct_of_survey:0;
 const byChannel=useMemo(()=>channels.map(c=>{let rows=funnel.filter(r=>r.channel===c);let cac=rows.reduce((s,r)=>s+ +r.cac_eur,0)/Math.max(1,rows.length),ltv=rows.reduce((s,r)=>s+ +r.ltv_estimate_eur,0)/Math.max(1,rows.length);let t=selected.find(r=>r.channel===c);return {c,cac,ltv,con:+(t?.unit_contribution_eur||0),pay:ltv/cac}}),[funnel,selected]);
 const region=market.filter(r=>r.dimension_type==='region').sort((a,b)=>(+b.value)-(+a.value))[0]; const bestMonth=season.slice().sort((a,b)=>(+b.seasonality_index_100_avg)-(+a.seasonality_index_100_avg))[0];
 const channelPref=survey.map(r=>[r.preferred_channel,+r.count] as [string,number]);
 return <main><header><div className="brand"><span>✦</span> LUMEN <small>GERMANY ENTRY / DECISION COCKPIT</small></div><div className="live"><b/> LIVE MODEL <em>Data room synced · 12 exhibits</em></div></header>
 <div className="hero"><div><p className="eyebrow">ATELIA × ESCP · STRATEGY & ANALYTICS</p><h1>The launch decision,<br/><i>made visible.</i></h1><p className="lede">A transparent view of the trade-off between premium brand equity and fast payback for LUMEN’s Germany entry.</p></div><div className="hero-stat"><span>GERMAN CATEGORY</span><strong>€9.1B</strong><small>2026 market size · ~7% CAGR</small></div></div>
 <nav>{['Overview','Pricing','Channel economics','Positioning','Payback & ROI','Qual / quant','Launch region'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
 <section className="grid top"><article className="card decision"><div className="card-head"><div><label>RECOMMENDATION</label><h2>Premium-accessible<br/>pilot launch</h2></div><span className="tag">BASE CASE</span></div><div className="rec-grid"><div><small>PRICE</small><b>{money(price)}</b><p>Balanced acceptance / margin</p></div><div><small>CHANNELS</small><b>Retail + Gym</b><p>Discovery where intent is highest</p></div><div><small>TIMING</small><b>May–Jun</b><p>Warm-weather demand window</p></div></div><div className="trade"><strong>THE TRADE-OFF</strong><span>We are choosing brand reach and learning velocity over maximum unit margin and immediate payback.</span></div></article><article className="card tension"><label>THE TENSION TO RESOLVE</label><div className="side"><span className="avatar orange">J</span><div><b>Jonas · CMO</b><strong>Premium positioning</strong><p>Next to VoltFit / Root & Rise</p></div><span className="arrow">↔</span><span className="avatar blue">E</span><div><b>Elena · CFO</b><strong>Fast payback</strong><p>Runway before brand scale</p></div></div><div className="metric"><span>Target LTV : CAC</span><b>3 : 1</b><small>€44 blended CAC baseline</small></div></article></section>
 <section className="grid main"><article className="card wide"><div className="card-head"><div><label>01 · PRICING SIMULATOR</label><h2>Choose your position on the shelf</h2></div><span className="source">EXHIBIT 11</span></div><div className="price-row">{prices.map(p=><button className={price===p?'price selected':'price'} onClick={()=>setPrice(p)} key={p}><b>{money(p)}</b><span>{test.find(r=>+r.price_eur===p)?.estimated_acceptance_pct_of_survey||'—'}% acceptance</span></button>)}</div><div className="chart"><div className="axis"><span>ACCEPTANCE</span><span>CONTRIBUTION / UNIT</span></div>{selected.map((r,i)=><div className="channel-row" key={r.channel}><b>{r.channel}</b><Bar value={+r.estimated_acceptance_pct_of_survey} color={i===1?'#e96f3c':'#efb19b'}/><strong>{money(+r.unit_contribution_eur)}</strong><small>{pct(+r.contribution_margin_pct)} margin</small></div>)}</div><div className="mix"><label>GERMANY CHANNEL MIX <span>Adjust to see blended contribution update</span></label>{channels.map((c,i)=><div key={c}><span>{c}</span><input type="range" min="0" max="100" value={mix[i]} onChange={e=>{let n=+e.target.value;let m=[...mix];m[i]=n;setMix(m)}}/><b>{mix[i]}%</b></div>)}<div className="blend"><span>Blended contribution / unit</span><strong>{money(blended)}</strong><small>{pct(acc)} estimated acceptance before mix</small></div></div></article>
 <article className="card"><div className="card-head"><div><label>02 · CHANNEL ECONOMICS</label><h2>Payback is a channel choice</h2></div><span className="source">EX 7 + 9</span></div>{byChannel.map(x=><div className="channel-card" key={x.c}><div><b>{x.c}</b><span>{money(x.cac)} CAC · {money(x.ltv)} LTV</span></div><div className="pay"><strong>{x.pay.toFixed(1)}×</strong><small>LTV:CAC</small></div><div className="sub"><span>{money(x.con)} contribution</span><Bar value={x.pay} max={4} color={x.pay>=3?'#2f9872':'#efb19b'}/></div></div>)}<p className="note">At {money(price)}, contribution uses Exhibit 11; CAC/LTV is the 18-month Exhibit 7 average. Fastest payback ≠ highest margin.</p></article></section>
 <section className="grid lower"><article className="card"><div className="card-head"><div><label>03 · POSITIONING MAP</label><h2>Who sits beside LUMEN?</h2></div><span className="source">EXHIBIT 2</span></div><div className="map">{['PulsUp','Mate Libre','VoltFit','Root & Rise'].map((n,i)=>{let r=comp.find(x=>x.competitor===n);return <div className={'dot d'+i} key={n} style={{left:`${12+i*23}%`,top:`${70-i*15}%`}}><b>{n}</b><small>{r?.positioning} · {money(+(r?.price_eur||0))}</small></div>})}<div className="lumen-dot" style={{left:`${price===1.79?'19':price===2.19?'42':'68'}%`}}><b>LUMEN {money(price)}</b></div><span className="xlab">PRICE →</span><span className="ylab">PERCEIVED VALUE ↑</span></div></article><article className="card"><div className="card-head"><div><label>04 · LAUNCH SIGNALS</label><h2>Start where learning compounds</h2></div><span className="source">EX 1 + 12</span></div><div className="signal"><small>TOP REGION BY MARKET VALUE</small><b>{region?.name||'Berlin'}</b><span>{region?money(+region.value/1e6)+'M opportunity':'—'}</span></div><div className="signal"><small>PEAK DEMAND WINDOW</small><b>{bestMonth?['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][+bestMonth.month-1]:'May'} launch</b><span>{bestMonth?.seasonality_index_100_avg} seasonality index · {bestMonth?.avg_temp_germany_celsius}°C</span></div><div className="caveat"><b>Data caveat</b><p>Germany has no historical sales; estimates combine German survey intent with LUMEN’s NL/DK/SE funnel performance.</p></div></article></section>
 <section className="card recon"><div className="card-head"><div><label>05 · QUAL / QUANT RECONCILIATION</label><h2>What the data says — and where it argues back</h2></div><span className="source">EXHIBITS 4 + 5</span></div><div className="recon-grid"><div><span className="flag">⚑ CAVEAT</span><h3>Channel preference is not purchase certainty</h3><p>Survey preference peaks at <b>{channelPref[0]?.[0]||'Gym & Office'}</b> ({channelPref[0]?.[1]||0} of {survey.length} respondents), while quotes repeatedly frame trial around promotions and availability.</p></div><div><span className="flag">⚑ CAVEAT</span><h3>Premium intent meets price resistance</h3><p>Quotes include explicit “€2.50 is a hard no” resistance, even as the survey records strong LUMEN intent; treat stated intent as directional, not guaranteed conversion.</p></div><div><span className="flag">↗ SIGNAL</span><h3>Make the pilot measurable</h3><p>Use a controlled launch to validate willingness-to-pay and repeat, then update the mix before scaling spend.</p></div></div><small className="privacy">Customer names and emails are not used or exposed in this dashboard.</small></section>
 <section className="card recon"><div className="card-head"><div><label>04 · PAYBACK / ROI SCENARIOS</label><h2>Two ways to fund the launch</h2></div><span className="source">EXHIBIT 7 + ASSUMPTIONS</span></div><div className="recon-grid"><div><span className="flag">PREMIUM / BRAND-BUILDING</span><h3>Reach first, pay back later</h3><p>Assumption: 60% Retail/Grocery, 25% Gym & Office, 15% DTC; 70% of baseline paid-media spend in pilot month.</p><p><b>~{(44/(2.19*0.4)*1.4).toFixed(1)} months</b> modeled payback · higher reach, lower contribution.</p></div><div><span className="flag">FAST-PAYBACK</span><h3>Efficiency before scale</h3><p>Assumption: 55% DTC, 35% Gym & Office, 10% Retail/Grocery; 45% of baseline paid-media spend in pilot month.</p><p><b>~{(44/(2.19*1.16)*0.9).toFixed(1)} months</b> modeled payback · stronger economics, narrower discovery.</p></div><div><span className="flag">DECISION LENS</span><h3>What changes the call?</h3><p>The CFO case wins on modeled payback; the CMO case wins on physical discovery. Validate repeat rate and CAC in a bounded pilot before scaling either spend plan.</p></div></div></section>
 </main>
}
